//! Canonical Milestone 12 markdown report writer.
//!
//! [`write_milestone12_results`] writes `report/milestone12_results.md`.
//! [`ValidationRow`] stores one row of multi-fidelity validation output.

use std::fmt::Write as FmtWrite;
use std::path::Path;

use serde::Serialize;

use crate::analysis::RobustnessReport;
use crate::constraints::M12_GA_HYDRO_SEED;
use crate::RankedDesign;

use super::ranking::oncology_priority_score;

#[derive(Debug, Clone, Serialize)]
pub struct ValidationRow {
    pub track: String,
    pub id: String,
    pub topology: String,
    pub dp_1d_bernoulli_pa: f64,
    pub dp_2d_fvm_pa: f64,
    pub dp_3d_fem_pa: f64,
    pub agreement_1d_2d_pct: f64,
    pub agreement_2d_3d_pct: f64,
    pub mass_error_3d_pct: f64,
    pub sigma_1d: f64,
    pub sigma_2d: f64,
    pub score: f64,
}

pub fn write_milestone12_results(
    total_candidates: usize,
    option1_pool_len: usize,
    option2_pool_len: usize,
    rbc_pool_len: usize,
    option1_ranked: &[RankedDesign],
    option2_ranked: &[RankedDesign],
    rbc_ranked: &[RankedDesign],
    ga_top: &RankedDesign,
    validation_rows: &[ValidationRow],
    option2_robustness: &[RobustnessReport],
    path: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut md = String::new();

    let option1 = option1_ranked
        .first()
        .ok_or("option1_ranked is empty; canonical report requires selected Option 1")?;
    let option2 = option2_ranked
        .first()
        .ok_or("option2_ranked is empty; strict-core Option 2 selection failed")?;
    let option2_rbc = rbc_ranked
        .first()
        .ok_or("rbc_ranked is empty; strict-core RBC track selection failed")?;

    writeln!(md, "# Milestone 12 Results - Canonical\n")?;
    writeln!(
        md,
        "> Generated by `cargo run -p cfd-optim --example milestone12_report --no-default-features`.\n"
    )?;

    writeln!(md, "## Milestone 12 Contract Trace")?;
    writeln!(
        md,
        "- **Description**: Select optimal design(s) that meet hydrodynamic and cavitation parameters."
    )?;
    writeln!(
        md,
        "- **Exit Criteria**: Design selected that meets hydrodynamic and cavitation parameters."
    )?;
    writeln!(
        md,
        "- **Deliverable**: Final report detailing process and limits of usage.\n"
    )?;

    writeln!(md, "## Dataset And Strict Eligibility")?;
    writeln!(md, "- Total generated candidates: **{}**", total_candidates)?;
    writeln!(
        md,
        "- Option 1 eligibility pool (no venturi + pressure/plate/FDA-main): **{}**",
        option1_pool_len
    )?;
    writeln!(
        md,
        "- Option 2 eligibility pool (CIF/CCT venturi + pressure/plate/FDA-main + sigma<1): **{}**",
        option2_pool_len
    )?;
    writeln!(
        md,
        "- RBC-protected venturi eligibility pool (CIF/CCT venturi + pressure/plate/FDA-main + sigma<1): **{}**\n",
        rbc_pool_len
    )?;

    writeln!(md, "## Selected Designs")?;
    writeln!(
        md,
        "| Track | Candidate | Topology | Mode | Active venturi throats | Score | sigma | WBC recovery | RBC venturi exposure | HI/pass | P95 shear (Pa) | ECV (mL) |"
    )?;
    writeln!(
        md,
        "|---|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|"
    )?;
    writeln!(
        md,
        "| Option 1 (Ultrasound branch, no venturi) | `{}` | {} | {} | {} | {:.4} | n/a | {:.4} | {:.4} | {:.2e} | {:.2} | {:.3} |",
        option1.candidate.id,
        option1.candidate.topology.name(),
        option1.metrics.treatment_zone_mode,
        option1.metrics.active_venturi_throat_count,
        option1.score,
        option1.metrics.wbc_recovery,
        option1.metrics.rbc_venturi_exposure_fraction,
        option1.metrics.hemolysis_index_per_pass,
        option1.metrics.wall_shear_p95_pa,
        option1.metrics.total_ecv_ml,
    )?;
    writeln!(
        md,
        "| Option 2 (Oncology-directed SDT, CIF/CCT venturi) | `{}` | {} | {} | {} | {:.4} | {:.4} | {:.4} | {:.4} | {:.2e} | {:.2} | {:.3} |",
        option2.candidate.id,
        option2.candidate.topology.name(),
        option2.metrics.treatment_zone_mode,
        option2.metrics.active_venturi_throat_count,
        option2.score,
        option2.metrics.cavitation_number,
        option2.metrics.wbc_recovery,
        option2.metrics.rbc_venturi_exposure_fraction,
        option2.metrics.hemolysis_index_per_pass,
        option2.metrics.wall_shear_p95_pa,
        option2.metrics.total_ecv_ml,
    )?;
    writeln!(
        md,
        "| Option 2 (Pure SDT / RBC-protected venturi) | `{}` | {} | {} | {} | {:.4} | {:.4} | {:.4} | {:.4} | {:.2e} | {:.2} | {:.3} |",
        option2_rbc.candidate.id,
        option2_rbc.candidate.topology.name(),
        option2_rbc.metrics.treatment_zone_mode,
        option2_rbc.metrics.active_venturi_throat_count,
        option2_rbc.score,
        option2_rbc.metrics.cavitation_number,
        option2_rbc.metrics.wbc_recovery,
        option2_rbc.metrics.rbc_venturi_exposure_fraction,
        option2_rbc.metrics.hemolysis_index_per_pass,
        option2_rbc.metrics.wall_shear_p95_pa,
        option2_rbc.metrics.total_ecv_ml,
    )?;
    writeln!(md)?;

    writeln!(md, "## Option 2 Ranked Top-5 (Deterministic Tie-Break)")?;
    writeln!(
        md,
        "Sorting policy: score desc, oncology-priority desc, RBC venturi exposure asc, clot risk asc, candidate id asc.\n"
    )?;
    writeln!(
        md,
        "| Rank | Candidate | Mode | Active venturi throats | Score | Oncology priority | RBC venturi exposure | Clot risk | sigma |"
    )?;
    writeln!(md, "|---:|---|---|---:|---:|---:|---:|---:|---:|")?;
    for d in option2_ranked.iter().take(5) {
        writeln!(
            md,
            "| {} | `{}` | {} | {} | {:.4} | {:.4} | {:.4} | {:.4} | {:.4} |",
            d.rank,
            d.candidate.id,
            d.metrics.treatment_zone_mode,
            d.metrics.active_venturi_throat_count,
            d.score,
            oncology_priority_score(&d.metrics),
            d.metrics.rbc_venturi_exposure_fraction,
            d.metrics.clotting_risk_index,
            d.metrics.cavitation_number,
        )?;
    }
    writeln!(md)?;

    writeln!(
        md,
        "## Strict-Core Gate Evidence (Selected Venturi Designs)"
    )?;
    writeln!(
        md,
        "| Track | Candidate | Pressure feasible | Plate fits | FDA main | sigma finite | sigma<1 |"
    )?;
    writeln!(md, "|---|---|---|---|---|---|---|")?;
    for (label, d) in [
        ("Option 2 Oncology-directed", option2),
        ("Option 2 RBC-protected", option2_rbc),
    ] {
        let m = &d.metrics;
        writeln!(
            md,
            "| {} | `{}` | {} | {} | {} | {} | {} |",
            label,
            d.candidate.id,
            if m.pressure_feasible { "PASS" } else { "FAIL" },
            if m.plate_fits { "PASS" } else { "FAIL" },
            if m.fda_main_compliant { "PASS" } else { "FAIL" },
            if m.cavitation_number.is_finite() {
                "PASS"
            } else {
                "FAIL"
            },
            if m.cavitation_number.is_finite() && m.cavitation_number < 1.0 {
                "PASS"
            } else {
                "FAIL"
            },
        )?;
    }
    writeln!(md)?;

    writeln!(
        md,
        "## Option 2 Robustness Screening (Perturbations +/-10%/+/-20%)"
    )?;
    let robust_count = option2_robustness.iter().filter(|r| r.is_robust).count();
    writeln!(
        md,
        "- Robust pass-rate: **{}/{}** candidates",
        robust_count,
        option2_robustness.len()
    )?;
    writeln!(
        md,
        "| Candidate | Nominal score | Min score | Max score | CV | Robust | Worst-case parameter |"
    )?;
    writeln!(md, "|---|---:|---:|---:|---:|---|---|")?;
    for r in option2_robustness {
        writeln!(
            md,
            "| `{}` | {:.4} | {:.4} | {:.4} | {:.4} | {} | {} |",
            r.candidate_id,
            r.score_nominal,
            r.score_min,
            r.score_max,
            r.score_cv,
            if r.is_robust { "YES" } else { "NO" },
            r.worst_case_param
        )?;
    }
    writeln!(md)?;

    writeln!(md, "## GA Reproducibility")?;
    writeln!(md, "- HydroSDT GA RNG seed: `{M12_GA_HYDRO_SEED}`")?;
    writeln!(
        md,
        "- GA rank-1: `{}` (score {:.4}, sigma {:.4})\n",
        ga_top.candidate.id, ga_top.score, ga_top.metrics.cavitation_number
    )?;

    writeln!(
        md,
        "## Multi-Fidelity Pressure-Drop Validation (Selected Venturi Designs)"
    )?;
    writeln!(
        md,
        "| Track | Candidate | dp1D Bernoulli (Pa) | dp2D FVM (Pa) | dp3D FEM (Pa) | 1D-2D diff (%) | 2D-3D diff (%) | Mass error (%) |"
    )?;
    writeln!(md, "|---|---|---:|---:|---:|---:|---:|---:|")?;
    for row in validation_rows {
        writeln!(
            md,
            "| {} | `{}` | {:.2} | {:.2} | {:.2} | {:.2} | {:.2} | {:.2} |",
            row.track,
            row.id,
            row.dp_1d_bernoulli_pa,
            row.dp_2d_fvm_pa,
            row.dp_3d_fem_pa,
            row.agreement_1d_2d_pct,
            row.agreement_2d_3d_pct,
            row.mass_error_3d_pct,
        )?;
    }
    writeln!(md)?;

    writeln!(
        md,
        "## Limits Of Usage (From Selected Option 2 Oncology-Directed Design)"
    )?;
    writeln!(
        md,
        "- Operating point: **{:.1} mL/min**, **{:.0} kPa gauge**",
        option2.candidate.flow_rate_m3_s * 6.0e7,
        option2.candidate.inlet_gauge_pa * 1.0e-3
    )?;
    writeln!(
        md,
        "- Venturi throat: **{:.0} um**, throat length **{:.0} um**",
        option2.candidate.throat_diameter_m * 1.0e6,
        option2.candidate.throat_length_m * 1.0e6
    )?;
    writeln!(
        md,
        "- Treatment mode: **{}**, active venturi throats: **{}** (serial stages per path: **{}**)",
        option2.metrics.treatment_zone_mode,
        option2.metrics.active_venturi_throat_count,
        option2.metrics.serial_venturi_stages_per_path
    )?;
    writeln!(
        md,
        "- FDA main-channel compliance: **{}**",
        if option2.metrics.fda_main_compliant {
            "PASS"
        } else {
            "FAIL"
        }
    )?;
    writeln!(
        md,
        "- Clot-risk indicators: `clotting_risk_index={:.4}`, `clotting_risk_index_10ml_s={:.4}`",
        option2.metrics.clotting_risk_index, option2.metrics.clotting_risk_index_10ml_s
    )?;
    writeln!(
        md,
        "- Flow caution flags: `Q>=200={}`, `Q>=600={}`",
        if option2.metrics.clotting_flow_compliant {
            "PASS"
        } else {
            "FAIL"
        },
        if option2.metrics.clotting_flow_compliant_10ml_s {
            "PASS"
        } else {
            "FAIL"
        }
    )?;

    std::fs::write(path, md)?;
    Ok(())
}
