//! Blueprint-native JSON and schematic export helpers.

use std::path::Path;

use serde::Serialize;

use crate::reporting::{Milestone12ReportDesign, ParetoPoint};
use cfd_1d::validate_blueprint_for_1d_solve;
use cfd_schematics::visualizations::{plot_blueprint_auto_annotated, RenderConfig};
use cfd_schematics::NetworkBlueprint;

/// Load a previously saved top-5 report JSON from disk.
///
/// Returns `Ok(Vec<..>)` on success, or `Ok(vec![])` if the file does not exist
/// (allowing downstream callers to treat a missing track as "not yet run").
///
/// # Errors
/// Returns an error only if the file exists but cannot be read or parsed.
pub fn load_top5_report_json(
    path: &Path,
) -> Result<Vec<Milestone12ReportDesign>, Box<dyn std::error::Error>> {
    if !path.exists() {
        return Ok(Vec::new());
    }
    let contents = std::fs::read_to_string(path)?;
    let designs: Vec<Milestone12ReportDesign> = serde_json::from_str(&contents)?;
    Ok(designs)
}

/// Serialise a blueprint-native Milestone 12 ranked design list to JSON.
///
/// # Errors
/// Returns an error if the file cannot be created or serialisation fails.
pub fn save_top5_report_json(
    designs: &[Milestone12ReportDesign],
    path: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    save_json_pretty(designs, path)
}

/// Serialise any serde value to pretty-printed JSON.
///
/// # Errors
/// Returns an error if the file cannot be created or serialisation fails.
pub fn save_json_pretty<T: Serialize + ?Sized>(
    value: &T,
    path: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let json = serde_json::to_string_pretty(value)?;
    std::fs::write(path, json)?;
    Ok(())
}

/// Save lightweight Pareto points to disk.
///
/// ~500x smaller than the full `Milestone12ReportDesign` pool: 32 bytes
/// per point vs ~16-20 KB per design.
pub fn save_pareto_points(
    points: &[ParetoPoint],
    path: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    save_json_pretty(points, path)
}

/// Load lightweight Pareto points from disk.
///
/// Returns `Ok(vec![])` if the file does not exist.
pub fn load_pareto_points(
    path: &Path,
) -> Result<Vec<ParetoPoint>, Box<dyn std::error::Error>> {
    if !path.exists() {
        return Ok(Vec::new());
    }
    let contents = std::fs::read_to_string(path)?;
    Ok(serde_json::from_str(&contents)?)
}

/// Render a schematic SVG for a fully materialized blueprint.
///
/// # Errors
/// Returns an error if the file cannot be written.
pub fn save_blueprint_schematic_svg(
    blueprint: &NetworkBlueprint,
    path: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    if !blueprint.is_geometry_authored() {
        return Err(format!(
            "canonical schematic export requires geometry-authored blueprint provenance; '{}' was not generated by create_geometry",
            blueprint.name
        )
        .into());
    }
    validate_blueprint_for_1d_solve(blueprint)?;
    let output_path = path.to_string_lossy();
    let mut config = RenderConfig::well_plate_96_report_annotated();
    config.title.clone_from(&blueprint.name);
    plot_blueprint_auto_annotated(blueprint, &output_path, &config)?;
    Ok(())
}
