//! Cavitation Risk Analysis in a Venturi Millifluidic Device -- 2D Navier-Stokes
//!
//! 2D counterpart of `cfd-1d::venturi_parallel_analysis` and
//! `cfd-1d::cavitation_venturi_analysis`. Uses the same millifluidic device
//! topology (inlet -> bifurcation split -> parallel frustum/venturi branches ->
//! outlets) generated by `cfd-schematics::create_geometry`, but resolves the
//! 2D throat velocity and pressure fields using `VenturiSolver2D` instead of
//! a lumped 1D resistance network.
//!
//! Pipeline:
//!   cfd-schematics `create_geometry` (AllFrustum) ->
//!   `VenturiSolver2D` (Newtonian water, 2D N-S) ->
//!   per-channel `VenturiCavitation` analysis ->
//!   AnalysisOverlay renders -> JSON export
//!
//! Run with:
//! `cargo run -p cfd-2d --example cavitation_venturi_2d`

use cfd_2d::solvers::ns_fvm_2d::BloodModel;
use cfd_2d::solvers::venturi_flow::{VenturiGeometry, VenturiSolver2D};
use cfd_core::physics::cavitation::VenturiCavitation;
use cfd_schematics::config::{ChannelTypeConfig, FrustumConfig, GeometryConfig, TaperProfile};
use cfd_schematics::geometry::generator::create_geometry;
use cfd_schematics::geometry::SplitType;
use cfd_schematics::plot_geometry;
use cfd_schematics::visualizations::analysis_field::{
    AnalysisField, AnalysisOverlay, ColormapKind,
};
use cfd_schematics::visualizations::plotters_backend::create_plotters_renderer;
use cfd_schematics::visualizations::traits::SchematicRenderer;
use cfd_schematics::visualizations::RenderConfig;
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("Cavitation Risk Analysis -- 2D Venturi Millifluidic Device");
    println!("==========================================================\n");

    let out = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("outputs");
    fs::create_dir_all(out.join("cavitation_venturi"))?;

    // -- Water at 25 C --
    let rho = 998.0_f64;
    let mu = 8.9e-4_f64;
    let p_vapor = 3169.0_f64; // vapor pressure at 25 C [Pa]
    let p_atm = 101_325.0_f64; // atmospheric reference for absolute pressure [Pa]

    // -- Frustum configuration: moderate venturi (2:1 contraction) --
    let frustum = FrustumConfig {
        inlet_width: 2.0,  // mm
        throat_width: 1.0, // mm
        outlet_width: 2.0, // mm
        taper_profile: TaperProfile::Smooth,
        smoothness: 80,
        throat_position: 0.5,
    };

    // -- 1. Generate Frustum Bifurcation Geometry --
    println!("1. Generating frustum bifurcation geometry...");
    let box_dims = (90.0, 42.0); // mm -- 96-well plate footprint
    let splits = vec![SplitType::Bifurcation];
    let mut geo_config = GeometryConfig::default();
    geo_config.channel_width = frustum.inlet_width;
    geo_config.channel_height = 0.5; // 500 um depth
    let channel_type = ChannelTypeConfig::AllFrustum(frustum.clone());

    let system = create_geometry(box_dims, &splits, &geo_config, &channel_type);
    println!(
        "   {} nodes, {} channels generated",
        system.nodes.len(),
        system.channels.len()
    );

    // -- 2. Render plain schematic --
    println!("2. Rendering plain schematic...");
    plot_geometry(
        &system,
        out.join("cavitation_venturi/schematic.png")
            .to_str()
            .unwrap(),
    )?;

    // -- 3. Flow distribution --
    println!("3. Computing bifurcation flow distribution...");
    let channel_levels = compute_channel_levels(&system);
    let max_level = channel_levels.values().copied().max().unwrap_or(0);

    let ch_h = geo_config.channel_height / 1000.0; // m
    let inlet_d = frustum.inlet_width / 1000.0;
    let throat_d = frustum.throat_width / 1000.0;
    let outlet_d = frustum.outlet_width / 1000.0;

    // -- 4. Run 2D Venturi Solver --
    println!("4. Running VenturiSolver2D (water, 2D N-S)...");
    let venturi_geom = VenturiGeometry::new(
        inlet_d,  // w_inlet [m]
        throat_d, // w_throat [m]
        5.0e-3,   // l_inlet [m]
        2.0e-3,   // l_converge [m]
        2.0e-3,   // l_throat [m]
        3.0e-3,   // l_diverge [m]
        ch_h,     // height [m]
    );
    let blood_model = BloodModel::Newtonian(mu);

    let u_inlet = 0.1; // 100 mm/s -- millifluidic inlet velocity
    let u_branch = u_inlet / 2.0_f64.powi(max_level as i32);

    println!(
        "   Fluid: Water 25C, rho = {:.0} kg/m3, mu = {:.1e} Pa.s",
        rho, mu
    );
    println!("   Contraction ratio: {:.1}:1", inlet_d / throat_d);
    println!("   Device inlet velocity: {:.1} mm/s", u_inlet * 1e3);

    let mut solver = VenturiSolver2D::new(venturi_geom, blood_model, rho, 60, 30);
    let sol = solver.solve(u_branch)?;

    println!("\n   2D Solver Results (representative branch):");
    println!("   u_inlet  = {:.4} m/s", sol.u_inlet);
    println!(
        "   u_throat = {:.4} m/s  ({:.1}x accel)",
        sol.u_throat,
        sol.u_throat / sol.u_inlet.max(1e-12)
    );
    println!("   p_inlet  = {:.2} Pa", sol.p_inlet);
    println!(
        "   p_throat = {:.2} Pa  (dP = {:.2} Pa)",
        sol.p_throat, sol.dp_throat
    );
    println!("   Cp_throat = {:.4}", sol.cp_throat);

    // -- 5. Per-channel cavitation analysis --
    println!("\n5. Per-channel VenturiCavitation analysis...");
    let mut edge_sigma = HashMap::<usize, f64>::new();
    let mut edge_velocity = HashMap::<usize, f64>::new();
    let mut edge_pressure = HashMap::<usize, f64>::new();
    let mut edge_dp = HashMap::<usize, f64>::new();
    let mut node_pressure = HashMap::<usize, f64>::new();

    // Node pressure: linear interpolation from x-position
    let min_x = system
        .nodes
        .iter()
        .map(|n| n.point.0)
        .fold(f64::INFINITY, f64::min);
    let max_x = system
        .nodes
        .iter()
        .map(|n| n.point.0)
        .fold(f64::NEG_INFINITY, f64::max);
    let inlet_pressure_gauge = sol.dp_throat.abs() * (max_level + 1) as f64 + 2000.0;
    for node in &system.nodes {
        let frac = (node.point.0 - min_x) / (max_x - min_x).max(1e-12);
        let p_node_gauge = inlet_pressure_gauge * (1.0 - frac);
        node_pressure.insert(node.id, p_atm + p_node_gauge);
    }

    println!("\n   Channel Results:");
    for channel in &system.channels {
        let level = channel_levels.get(&channel.id).copied().unwrap_or(0);
        let v_scale = u_inlet / 2.0_f64.powi(level as i32);

        // Scale 2D throat conditions by velocity ratio
        let v_throat = sol.u_throat * (v_scale / u_branch);
        let channel_p = node_pressure
            .get(&channel.from_node)
            .copied()
            .unwrap_or(p_atm + inlet_pressure_gauge);

        // VenturiCavitation analysis
        let venturi = VenturiCavitation {
            inlet_diameter: inlet_d,
            throat_diameter: throat_d,
            outlet_diameter: outlet_d,
            convergent_angle: 0.2618, // ~15 deg
            divergent_angle: 0.1222,  // ~7 deg
            inlet_pressure: channel_p,
            inlet_velocity: v_scale,
            density: rho,
            vapor_pressure: p_vapor,
        };

        let sigma = venturi.cavitation_number();
        let is_cav = venturi.is_cavitating();
        let cavity_len = venturi.cavity_length(sigma);
        let dp = sol.dp_throat.abs() * (v_scale / u_branch);

        println!(
            "   chan_{} (level {}) | v_throat={:.2} m/s | sigma={:.3} | cav={}",
            channel.id, level, v_throat, sigma, is_cav
        );
        if cavity_len > 0.0 {
            println!("     Cavity length: {:.3} mm", cavity_len * 1000.0);
        }

        edge_sigma.insert(channel.id, sigma);
        edge_velocity.insert(channel.id, v_throat);
        edge_pressure.insert(channel.id, channel_p);
        edge_dp.insert(channel.id, dp);
    }

    // -- 6. Render overlays --
    println!("\n6. Rendering analysis overlays...");
    let renderer = create_plotters_renderer();

    let overlay_specs: Vec<(&str, AnalysisField, &HashMap<usize, f64>, ColormapKind)> = vec![
        (
            "cavitation_sigma",
            AnalysisField::Custom("sigma".to_string()),
            &edge_sigma,
            ColormapKind::BlueRed,
        ),
        (
            "throat_velocity",
            AnalysisField::Velocity,
            &edge_velocity,
            ColormapKind::Viridis,
        ),
        (
            "pressure",
            AnalysisField::Pressure,
            &edge_pressure,
            ColormapKind::BlueRed,
        ),
        (
            "pressure_drop",
            AnalysisField::Custom("dP".to_string()),
            &edge_dp,
            ColormapKind::Viridis,
        ),
    ];

    for (filename, field, data, cmap) in &overlay_specs {
        let overlay = AnalysisOverlay::new(field.clone(), *cmap)
            .with_edge_data((*data).clone())
            .with_node_data(node_pressure.clone());
        let mut rc = RenderConfig::default();
        rc.title = format!("Venturi 2D -- {filename}");
        rc.show_axes = true;
        rc.show_grid = false;
        let path = out.join(format!("cavitation_venturi/{filename}.png"));
        renderer.render_analysis(&system, path.to_str().unwrap(), &rc, &overlay)?;
        println!("   [ok] {filename}.png");
    }

    // -- 7. JSON Export --
    println!("\n7. Exporting JSON results...");
    let channel_report: Vec<serde_json::Value> = system
        .channels
        .iter()
        .map(|ch| {
            serde_json::json!({
                "channel_id": ch.id,
                "bifurcation_level": channel_levels.get(&ch.id),
                "cavitation_number": edge_sigma.get(&ch.id),
                "throat_velocity_ms": edge_velocity.get(&ch.id),
                "pressure_pa": edge_pressure.get(&ch.id),
                "pressure_drop_pa": edge_dp.get(&ch.id),
            })
        })
        .collect();

    let report = serde_json::json!({
        "analysis": "cavitation_venturi_2d",
        "solver": "VenturiSolver2D (2D Navier-Stokes)",
        "device": {
            "topology": "frustum bifurcation (inlet -> split -> 2 venturi branches -> outlets)",
            "box_mm": [box_dims.0, box_dims.1],
            "frustum": {
                "inlet_width_mm": frustum.inlet_width,
                "throat_width_mm": frustum.throat_width,
                "outlet_width_mm": frustum.outlet_width,
                "contraction_ratio": frustum.inlet_width / frustum.throat_width,
            },
            "num_nodes": system.nodes.len(),
            "num_channels": system.channels.len()
        },
        "fluid": {
            "type": "Water 25C",
            "density_kg_m3": rho,
            "viscosity_pa_s": mu,
            "vapor_pressure_pa": p_vapor,
            "pressure_reference_pa": p_atm,
        },
        "solver_2d": {
            "grid": "60 x 30",
            "u_branch_ms": u_branch,
            "u_throat_ms": sol.u_throat,
            "p_throat_pa": sol.p_throat,
            "dp_throat_pa": sol.dp_throat,
            "cp_throat": sol.cp_throat,
        },
        "channels": channel_report,
    });

    let json_path = out.join("cavitation_venturi/results.json");
    fs::write(&json_path, serde_json::to_string_pretty(&report)?)?;
    println!("   Exported to {}", json_path.display());

    println!("\nCavitation analysis complete -- all outputs in cavitation_venturi/");
    Ok(())
}

/// Assign bifurcation levels to channels via BFS from inlet nodes.
fn compute_channel_levels(
    system: &cfd_schematics::geometry::types::ChannelSystem,
) -> HashMap<usize, usize> {
    let min_x = system
        .nodes
        .iter()
        .map(|n| n.point.0)
        .fold(f64::INFINITY, f64::min);
    let inlet_ids: Vec<usize> = system
        .nodes
        .iter()
        .filter(|n| (n.point.0 - min_x).abs() < 1e-3)
        .map(|n| n.id)
        .collect();

    let mut levels = HashMap::new();
    let mut current = inlet_ids;
    let mut level = 0;

    while !current.is_empty() {
        let mut next = Vec::new();
        for &node_id in &current {
            for chan in &system.channels {
                if chan.from_node == node_id && !levels.contains_key(&chan.id) {
                    levels.insert(chan.id, level);
                    next.push(chan.to_node);
                }
            }
        }
        level += 1;
        current = next;
    }

    levels
}
